# East
vil = ('VIL',"https://www.sports-reference.com/cbb/schools/villanova/2018.html")
radford = ('RAD',"https://www.sports-reference.com/cbb/schools/radford/2018.html")
virtec = ('VIRTEC',"https://www.sports-reference.com/cbb/schools/virginia-tech/2018.html")
alabama = ('ALA',"https://www.sports-reference.com/cbb/schools/alabama/2018.html")
westvirg = ('WVA',"https://www.sports-reference.com/cbb/schools/west-virginia/2018.html")
murray = ('MURRAY',"https://www.sports-reference.com/cbb/schools/murray-state/2018.html")
wichita = ('WICHITA',"https://www.sports-reference.com/cbb/schools/wichita-state/2018.html")
marshall = ('MARSHALL',"https://www.sports-reference.com/cbb/schools/marshall/2018.html")
florida = ('FLORIDA',"https://www.sports-reference.com/cbb/schools/florida/2018.html")
bonaventure = ('BONA',"https://www.sports-reference.com/cbb/schools/st-bonaventure/2018.html")
texastech = ('TEXTEC',"https://www.sports-reference.com/cbb/schools/texas-tech/2018.html")
steveaustin = ('STEVEAUSTIN',"https://www.sports-reference.com/cbb/schools/stephen-f-austin/2018.html")
arkansas = ('ARKANSAS',"https://www.sports-reference.com/cbb/schools/arkansas/2018.html")
butler = ('BUTLER',"https://www.sports-reference.com/cbb/schools/butler/2018.html")
purdue = ('PURDUE',"https://www.sports-reference.com/cbb/schools/purdue/2018.html")
fullerton = ('FULLERTON',"https://www.sports-reference.com/cbb/schools/cal-state-fullerton/2018.html")

# Midwest
kansas = ('KANSAS',"https://www.sports-reference.com/cbb/schools/kansas/2018.html")
penn = ('PENN',"https://www.sports-reference.com/cbb/schools/pennsylvania/2018.html")
setonhall = ('SETON',"https://www.sports-reference.com/cbb/schools/seton-hall/2018.html")
ncstate = ('NCSTATE',"https://www.sports-reference.com/cbb/schools/north-carolina-state/2018.html")
clemson = ('CLEM',"https://www.sports-reference.com/cbb/schools/clemson/2018.html")
nmstate = ('NMSATE',"https://www.sports-reference.com/cbb/schools/new-mexico-state/2018.html")
auburn = ('AUBURN',"https://www.sports-reference.com/cbb/schools/auburn/2018.html")
charleston = ('CHARLESTON',"https://www.sports-reference.com/cbb/schools/college-of-charleston/2018.html")
texchrist = ('TEXAS CHRISTIAN',"https://www.sports-reference.com/cbb/schools/texas-christian/2018.html")
syracuse = ("SYRACUSE", "https://www.sports-reference.com/cbb/schools/syracuse/2018.html")
msu = ('MSU',"https://www.sports-reference.com/cbb/schools/michigan-state/2018.html")
bucknell = ('BUCKNELL',"https://www.sports-reference.com/cbb/schools/bucknell/2018.html")
rhode = ("RHODE ISLAND", "https://www.sports-reference.com/cbb/schools/rhode-island/2018.html")
oklahoma = ('OK',"https://www.sports-reference.com/cbb/schools/oklahoma/2018.html")
duke = ('DUKE',"https://www.sports-reference.com/cbb/schools/duke/2018.html")
iona = ('IONA',"https://www.sports-reference.com/cbb/schools/iona/2018.html")

# West
xavier = ('XAVIER', "https://www.sports-reference.com/cbb/schools/xavier/2018.html")
texassouthern = ("TEXAS SOUTHERN", "https://www.sports-reference.com/cbb/schools/texas-southern/2018.html")
missouri = ('MISSOURI', "https://www.sports-reference.com/cbb/schools/missouri/2018.html")
floridastate = ('FLORIDA STATE', "https://www.sports-reference.com/cbb/schools/florida-state/2018.html")
ohiostate = ('OHIO STATE', "https://www.sports-reference.com/cbb/schools/ohio-state/2018.html")
sdstate = ('SD STATE', "https://www.sports-reference.com/cbb/schools/south-dakota-state/2018.html")
gonzaga = ('GONZAGA', "https://www.sports-reference.com/cbb/schools/gonzaga/2018.html")
ncgreen = ('GREENSBORO', "https://www.sports-reference.com/cbb/schools/north-carolina-greensboro/2018.html")
houston = ('HOUSTON', "https://www.sports-reference.com/cbb/schools/houston/2018.html")
sandstate = ('SAN DIEGO', "https://www.sports-reference.com/cbb/schools/san-diego-state/2018.html")
michigan = ('MICHIGAN', "https://www.sports-reference.com/cbb/schools/michigan/2018.html")
montana = ('MONTANA', "https://www.sports-reference.com/cbb/schools/montana/2018.html")
taam = ('A&M', "https://www.sports-reference.com/cbb/schools/texas-am/2018.html")
providence = ('PROVIDENCE', "https://www.sports-reference.com/cbb/schools/providence/2018.html")
unc = ('UNC', "https://www.sports-reference.com/cbb/schools/north-carolina/2018.html")
linscomb = ('LINSCOMB', "https://www.sports-reference.com/cbb/schools/lipscomb/2018.html")

# South
virginia = ("VIRGINIA", "https://www.sports-reference.com/cbb/schools/virginia/2018.html")
umbc = ("UMBC", "https://www.sports-reference.com/cbb/schools/maryland-baltimore-county/2018.html")
creighton = ("CREIGHTON", "https://www.sports-reference.com/cbb/schools/creighton/2018.html")
kansasstate = ("KANSAS STATE", "https://www.sports-reference.com/cbb/schools/kansas-state/2018.html")
kentucky = ("KENTUCKY", "https://www.sports-reference.com/cbb/schools/kentucky/2018.html")
davidson = ("DAVIDSON", "https://www.sports-reference.com/cbb/schools/davidson/2018.html")
arizona = ("ARIZONA", "https://www.sports-reference.com/cbb/schools/arizona/2018.html")
buffalo = ("BUFFALO", "https://www.sports-reference.com/cbb/schools/buffalo/2018.html")
miami = ("MIAMI", "https://www.sports-reference.com/cbb/schools/miami-fl/2018.html")
loyola = ("LOYOLA", "https://www.sports-reference.com/cbb/schools/loyola-il/2018.html")
tennessee = ("TENNESSEE", "https://www.sports-reference.com/cbb/schools/tennessee/2018.html")
wright = ("WRIGHT", "https://www.sports-reference.com/cbb/schools/wright-state/2018.html")
nevada = ("NEVADA", "https://www.sports-reference.com/cbb/schools/nevada/2018.html")
texas = ("TEXAS", "https://www.sports-reference.com/cbb/schools/texas/2018.html")
cinci = ("CINCI", "https://www.sports-reference.com/cbb/schools/cincinnati/2018.html")
georgia = ("GEORGIA STATE", "https://www.sports-reference.com/cbb/schools/georgia-state/2018.html")